# Dependabot configuration for Nodea MVP 2.1
# This file configures automated dependency updates and security alerts

version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "elliottbrycecrosby"
    assignees:
      - "elliottbrycecrosby"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Security updates are always allowed
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates for critical dependencies
    ignore:
      - dependency-name: "convex"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "reactflow"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@convex-dev/auth"
        update-types: ["version-update:semver-major"]
      - dependency-name: "dompurify"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "elliottbrycecrosby"
    assignees:
      - "elliottbrycecrosby"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
