import type { Metadata } from 'next'
import Nav from '@/app/_components/landing/Nav'
import Footer from '@/app/_components/landing/Footer'
import '@/app/_components/landing/landing.css'

export const metadata: Metadata = {
  title: 'Terms of Service — Nodea',
  description:
    'The terms that govern your use of Nodea, the branching AI chat canvas at nodea.ai, and the "Nodea Tree for Claude" browser extension.',
  alternates: { canonical: '/terms' },
  robots: { index: true, follow: true },
}

const LAST_UPDATED = 'June 3, 2026'

export default function TermsPage() {
  return (
    <div className="ln-root">
      <Nav />

      <main>
        <section style={{ padding: '80px 0 64px' }}>
          <div className="ln-container" style={{ maxWidth: 760 }}>
            <span className="ln-kicker">Legal</span>
            <h1 style={{ fontSize: '2.4rem', margin: '0.4em 0 0.2em', letterSpacing: '-0.02em' }}>
              Terms of Service
            </h1>
            <p style={{ color: 'var(--text-muted)', marginBottom: '2.5rem' }}>
              Last updated: {LAST_UPDATED}
            </p>

            <div className="ln-legal">
              <p>
                These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Nodea
                (&ldquo;Nodea,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;), including
                the web app at <a href="https://nodea.ai">nodea.ai</a> and the{' '}
                <strong>&ldquo;Nodea Tree for Claude&rdquo;</strong>{' '}
                browser extension. By creating an account or using Nodea, you agree
                to these Terms. If you don&rsquo;t agree, please don&rsquo;t use the service.
              </p>

              <h2>What Nodea is</h2>
              <p>
                Nodea is a branching AI chat canvas. Every reply becomes a node you
                can fork from — your conversation grows as a tree of branches, not one
                long thread. Replies are generated by third-party AI models (currently
                Anthropic&rsquo;s Claude).
              </p>

              <h2>Your account</h2>
              <ul>
                <li>You&rsquo;re responsible for the activity under your account and for keeping your login credentials secure.</li>
                <li>You must be old enough to form a binding contract where you live (at least 13, and the age of digital consent in your jurisdiction).</li>
                <li>Provide accurate information and keep it current.</li>
              </ul>

              <h2>Acceptable use</h2>
              <p>You agree not to:</p>
              <ul>
                <li>Use Nodea to break the law, infringe others&rsquo; rights, or generate harmful, abusive, or deceptive content.</li>
                <li>Disrupt, overload, reverse-engineer, or gain unauthorized access to the service or its infrastructure.</li>
                <li>Resell, scrape, or redistribute the service in bulk without our written permission.</li>
                <li>
                  Violate the usage policies of the underlying AI providers, including{' '}
                  <a
                    href="https://www.anthropic.com/legal/aup"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Anthropic&rsquo;s Usage Policy
                  </a>
                  .
                </li>
              </ul>

              <h2>Your content</h2>
              <p>
                You keep ownership of the conversations and content you create in
                Nodea. You grant us the limited rights needed to operate the service —
                storing your conversations, displaying them back to you, and sending
                your prompts to our AI provider to generate replies. We do not sell
                your content or use it for advertising. See our{' '}
                <a href="/privacy">Privacy Policy</a> for the details.
              </p>

              <h2>AI output</h2>
              <p>
                AI-generated responses can be inaccurate, incomplete, or
                inappropriate, and may not reflect current facts. Output is provided
                for your own evaluation — do not rely on it as professional, legal,
                medical, or financial advice. You&rsquo;re responsible for how you use
                anything Nodea generates.
              </p>

              <h2>Plans, billing &amp; refunds</h2>
              <ul>
                <li>Nodea offers free and paid plans. Paid plans are billed in advance through our payment processor, Stripe, on a recurring basis until canceled.</li>
                <li>You can cancel at any time. Cancellation stops future charges and takes effect at the end of the current billing period.</li>
                <li>Except where required by law, payments are non-refundable. Prices and plan features may change, with notice to active subscribers.</li>
              </ul>

              <h2>Third parties &amp; Anthropic</h2>
              <p>
                Nodea relies on third-party providers (including Anthropic, Supabase,
                Stripe, and Vercel) to operate. Nodea and the &ldquo;Nodea Tree for
                Claude&rdquo; extension are not affiliated with, endorsed by, or
                sponsored by Anthropic. &ldquo;Claude&rdquo; is a trademark of
                Anthropic, PBC.
              </p>

              <h2>Service availability</h2>
              <p>
                We work to keep Nodea available and reliable, but the service is
                provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
                warranties of any kind. We may change, suspend, or discontinue
                features at any time.
              </p>

              <h2>Limitation of liability</h2>
              <p>
                To the fullest extent permitted by law, Nodea and its operators are
                not liable for any indirect, incidental, or consequential damages, or
                for loss of data, profits, or content, arising from your use of the
                service. Our total liability for any claim is limited to the amount
                you paid us in the twelve months before the claim.
              </p>

              <h2>Termination</h2>
              <p>
                You can stop using Nodea and delete your account at any time. We may
                suspend or terminate accounts that violate these Terms or that we are
                required to act on by law. To delete your account and associated data,
                email us at the address below.
              </p>

              <h2>Changes to these Terms</h2>
              <p>
                We may update these Terms from time to time. Material changes will be
                reflected by the &ldquo;Last updated&rdquo; date above; continuing to
                use Nodea after a change means you accept the revised Terms.
              </p>

              <h2>Contact</h2>
              <p>
                Questions about these Terms?{' '}
                <a href="mailto:nodea.ai@gmail.com">nodea.ai@gmail.com</a>.
              </p>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
