-- Tree state summary: a short "where this stands" briefing plus a few "open
-- loops" (threads raised but not resolved/explored), generated by Haiku and
-- shown when a user re-opens a conversation. A re-entry hook to fight the
-- cold-start that kills the second visit.
--
-- Reminder: the legacy `projects` table actually stores conversations (trees).
--
-- summary_node_count is the node count at generation time — used to detect
-- staleness cheaply: regenerate only when the tree has changed since.
ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS summary            TEXT,
  ADD COLUMN IF NOT EXISTS summary_open_loops JSONB,
  ADD COLUMN IF NOT EXISTS summary_node_count INTEGER,
  ADD COLUMN IF NOT EXISTS summary_updated_at TIMESTAMPTZ;
